### ISSUE TITLE
Missing Lightning Queue reply channel after bootstrapping

### ISSUE THREAD

**Issue by smerrell** [DarthFubuMVC/fubumvc#976]
Still digging into this but it looks like occasionally when bootstrapping a Fubu 3 app we are not getting the Reply Channel set up properly for Lightning Queues. When we try to send a message we get this exception:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: No known reply channel for protocol 'lq.tcp'
   at FubuMVC.Core.ServiceBus.Configuration.ChannelGraph.<>c.<.ctor>b__2_1(String name) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\ServiceBus\Configuration\ChannelGraph.cs:line 23
   at FubuCore.Util.Cache`2.Fill(TKey key, Func`2 onMissing) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\Util\Cache.cs:line 130
   at FubuCore.Util.Cache`2.get_Item(TKey key) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\Util\Cache.cs:line 85
   at FubuMVC.Core.ServiceBus.Runtime.EnvelopeSender.sendToChannel(Envelope envelope, ChannelNode node) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\ServiceBus\Runtime\EnvelopeSender.cs:line 66
   at FubuMVC.Core.ServiceBus.Runtime.EnvelopeSender.<>c__DisplayClass5_0.<Send>b__1(ChannelNode x) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\ServiceBus\Runtime\EnvelopeSender.cs:line 50
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction) in c:\BuildAgent\work\4dafc5966c0aefb4\src\FubuCore\EnumerableExtensions.cs:line 76
   at FubuMVC.Core.ServiceBus.Runtime.EnvelopeSender.Send(Envelope envelope) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\ServiceBus\Runtime\EnvelopeSender.cs:line 54
   at ************.***********.**************.****************************.SendSuccessfulLogin(User user, Int32 employeePersonId) in d:\BuildAgent\work\95dadf261f5ac068\src\************************\**************\****************************.cs:line 35
   at ************.***********.**************.**********************.Audit(LoginRequest request) in d:\BuildAgent\work\95dadf261f5ac068\src\************************\**************\**********************.cs:line 40
   at FubuMVC.Core.Security.Authentication.AuthenticationService.Authenticate(LoginRequest request, IEnumerable`1 strategies) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Security\Authentication\AuthenticationService.cs:line 63
   at FubuMVC.Core.Security.Authentication.Endpoints.LoginController.post_login(LoginRequest request) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Security\Authentication\Endpoints\LoginController.cs:line 27
   at FubuMVC.Core.Behaviors.OneInOneOutActionInvoker`3.performInvoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\OneInOneOutActionInvoker.cs:line 25
   at FubuMVC.Core.Behaviors.BasicBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 26
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Behaviors.BasicBehavior.<.ctor>b__2_0() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 19
   at FubuMVC.Core.Behaviors.BasicBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 31
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Behaviors.BasicBehavior.<.ctor>b__2_0() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 19
   at FubuMVC.Core.Behaviors.BasicBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 31
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Behaviors.BasicBehavior.<.ctor>b__2_0() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 19
   at FubuMVC.Core.Behaviors.BasicBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 31
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Behaviors.BasicBehavior.<.ctor>b__2_0() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 19
   at FubuMVC.Core.Behaviors.BasicBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 31
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.RavenDb.TransactionalBehavior.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.RavenDb\TransactionalBehavior.cs:line 25
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Behaviors.BasicBehavior.<.ctor>b__2_0() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 19
   at FubuMVC.Core.Behaviors.BasicBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\BasicBehavior.cs:line 31
   at FubuMVC.Core.Diagnostics.Instrumentation.BehaviorTracer.invoke(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Diagnostics\Instrumentation\BehaviorTracer.cs:line 29
   at FubuMVC.Core.Behaviors.WrappingBehavior.Invoke() in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Behaviors\WrappingBehavior.cs:line 15
   at FubuMVC.Core.Runtime.BehaviorInvoker.Invoke(ServiceArguments arguments, IDictionary`2 routeValues, IRequestCompletion requestCompletion) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Runtime\BehaviorInvoker.cs:line 64
   at FubuMVC.Core.Runtime.RequestCompletion.Start(Action action) in C:\BuildAgent\work\aff5105d8a204129\src\FubuMVC.Core\Runtime\RequestCompletion.cs:line 34
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
2016-06-10 15:51:58.6283 ERROR System.String - Failed trying to send message Envelope for message ************.***********.********.********.********************* (*********************) w/ Id d90e7d1d-2b2c-47e7-b911-c51624bd5ec5 to channel lq.tcp://**********.************.com:2430/************ 
```

Tracing it back through the EnvelopeSender to the SubscriptionCache method ReplyUriFor the ChannelGraph doesn't seem to have the ReplyChannel set up. From what I see, the LightningQueues ReplyChannel should be created when the LightningQueuesTransport class is constructed. Since the LightningQueuesTransport is included in the LightningQueuesServiceRegistry, I would think it is created on bootstrap. I'm going to keep looking into why that might be missing, but any help would be appreciated.

I also will try to update this as I learn anything new. Thanks!

**Theory**
Could trying to send a message before bootstrapping has finished cause the cache miss? Since it is a cache, it would then hold onto that lambda that throws every time.

Or perhaps a load balanced situation where one bootstrapped app pool tries to hit a route that sends a message on an un-bootstrapped app pool.

**Comment by RyanHauert** [comment]
I haven't verified this entirely, just glanced through the code to look at where it starts processing messages (QueueManager.Start()) and I found this: https://github.com/DarthFubuMVC/fubumvc/blob/master/src/FubuMVC.Core/ServiceBus/Runtime/TransportBase.cs#L18

It looks like because `seedQueues` is called before `graph.AddReplyChannel` some messages that start getting processed right as the queue manager starts could hit this error.

**Comment by jeremydmiller** [comment]
@RyanHauert @smerrell Sorry guys, but this can't be the answer to the problem that Sam is hitting. In the TransportBase code, the `OpenChannels()` method is called to *start* the channels, but Fubu isn't starting message processing until after that method.

Regardless, Sam's error message happened from a FubuMVC HTTP request, and that wouldn't be possible until completely after all the activators, including the transport activator that spins up the channels, has completed.

For right now, I'm pushing a change that just adds more information about the current configuration when that exception is thrown to try to gather more contextual information.

**Comment by smerrell** [comment]
Thanks Jeremy! Steve and his team are going to see if they can reproduce the issue locally so the updated code should help them out -- if they can end up reproducing it locally that is. Otherwise we get more info in production :)

**Comment by CoreyKaylor** [comment]
Closing this since there has been no update.

**Comment by smerrell** [comment]
👍 I'll reopen this once we actually get the updated nugets in production and get more information. I've seen the lq issue a few more times but since we don't have the updated logging it hasn't been very helpful to figure out what is going on.
